version: '3'
services:
  proxy:
    build: proxy/.
    ports:
     - "80"
     - "443"
    links:
     - "torreja:torreja"
  dns:
    build: dns/.
    ports:
     - "53"
    depends_on:
     - proxy
    links:
      - "proxy:proxy"
  torreja:
    build: torreja/.
  compras:
    build: compras/.
    ports:
      - "443"
