version: '3'
services:
  proxy:
    build: proxy/.
    ports:
     - "80:80"
    links:
     - "torreja:torreja"
  dns:
    build: dns/.
    ports:
     - "53:53"
    depends_on:
     - proxy 
    links:
      - "proxy:proxy"
  torreja:
    build: torreja/.
    
   
    
