FROM debian:stretch
MAINTAINER henrijacobo@hotmail.com
RUN apt-get update && apt-get install -yq apt-utils apache2 tcpdump && apt-get clean
COPY torreja.sh /torreja.sh
CMD ["./torreja.sh"]
EXPOSE 80
ENTRYPOINT ["/bin/bash"]
